{{- if .Values.wireguard.config.privateKey }}
{{- $fullName := include "wg-access-server.fullname" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ $fullName }}"
  labels:
    {{- include "wg-access-server.labels" . | nindent 4 }}
type: Opaque
data:
  privateKey: {{ .Values.wireguard.config.privateKey | b64enc | quote }}
{{- end }}
